apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: nginx-autoscaling
  namespace: meow
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
