apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meow-ingress
  namespace: meow
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: meocon.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 8000